extract_unity_shaders: Fix regression extracting OpenGL shaders
The commit "extract_untiy53_shader: Refactor to use sub_program data
structures" (ee6a6ef0883057b6dd6cf66dcb825de0886b94d6) introduced a
regression in extract_unity_shaders.py when extracting OpenGL shaders,
resulting in the following error:

Parsing resources/Sh_PD_GUI_flatcolor.shader...
Traceback (most recent call last):
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 1036, in <module>
    sys.exit(main())
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 986, in main
    tree = parse_tree(filename, data, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 917, in parse_tree
    return parse_keywords(tree, filename=os.path.basename(filename), args=args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 263, in parse_keywords
    item = keywords[token](token, tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 104, in __init__
    return self.parse(tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 129, in parse
    Tree.__init__(self, parse_keywords(next_interesting(tokens), parent=self, args=args))
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 263, in parse_keywords
    item = keywords[token](token, tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 104, in __init__
    return self.parse(tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 154, in parse
    Tree.__init__(self, parse_keywords(next_interesting(tokens), parent=self, args=args))
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 263, in parse_keywords
    item = keywords[token](token, tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 104, in __init__
    return self.parse(tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 154, in parse
    Tree.__init__(self, parse_keywords(next_interesting(tokens), parent=self, args=args))
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 263, in parse_keywords
    item = keywords[token](token, tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 104, in __init__
    return self.parse(tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 129, in parse
    Tree.__init__(self, parse_keywords(next_interesting(tokens), parent=self, args=args))
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 263, in parse_keywords
    item = keywords[token](token, tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 104, in __init__
    return self.parse(tokens, parent, args)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 129, in parse
    Tree.__init__(self, parse_keywords(next_interesting(tokens), parent=self, args=args))
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 256, in parse_keywords
    handle_shader_asm(token, parent, strip_quotes(token))
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 214, in handle_shader_asm
    add_shader_hash(parent)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 657, in add_shader_hash
    return add_shader_hash_gl_crc(sub_program)
  File "/home/dss/3d-fixes/extract_unity_shaders.py", line 638, in add_shader_hash_gl_crc
    _add_shader_hash_gl_crc(hash_gl_crc(sub_program))
TypeError: _add_shader_hash_gl_crc() missing 1 required positional argument: 'hash'

Fix the arguments passed to _add_shader_hash_gl_crc.